using System.Net;
using System.Text;

namespace CodeCompass.Bench;

public sealed record ReportMeta(string Timestamp, string Machine, string Os, int Cores, string Runtime);

/// <summary>One repo's row in the report: perf plus a correctness verdict.</summary>
public sealed record ReportRow(string Id, string Language, BenchResult Bench, string Correctness);

/// <summary>
/// Renders a single self-contained HTML page (inline CSS, no external assets) so it can
/// be dropped straight into an email or message.
/// </summary>
public static class HtmlReport
{
    public static string Generate(IReadOnlyList<ReportRow> rows, ReportMeta meta, IReadOnlyList<string> skipped)
    {
        var sb = new StringBuilder();
        sb.Append("<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\">");
        sb.Append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
        sb.Append("<title>CodeCompass benchmark</title>");
        sb.Append("<style>");
        sb.Append("""
            :root{--bg:#0f1720;--card:#1b2430;--ink:#e6edf3;--muted:#9fb0c0;--line:#2b3947;--good:#2ea043;--bad:#e5534b;--accent:#4c8bf5}
            *{box-sizing:border-box}
            body{margin:0;background:var(--bg);color:var(--ink);font:14px/1.5 -apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;padding:28px}
            .wrap{max-width:1100px;margin:0 auto}
            h1{font-size:20px;margin:0 0 4px} .sub{color:var(--muted);margin:0 0 20px}
            .meta{display:flex;flex-wrap:wrap;gap:10px;margin:0 0 20px}
            .chip{background:var(--card);border:1px solid var(--line);border-radius:8px;padding:6px 10px;color:var(--muted)}
            .chip b{color:var(--ink);font-weight:600}
            table{width:100%;border-collapse:collapse;background:var(--card);border:1px solid var(--line);border-radius:10px;overflow:hidden}
            th,td{padding:9px 10px;text-align:right;border-bottom:1px solid var(--line);white-space:nowrap}
            th{background:#141d28;color:var(--muted);font-weight:600;font-size:12px;text-transform:uppercase;letter-spacing:.03em}
            td:first-child,th:first-child,td:nth-child(2),th:nth-child(2){text-align:left}
            tr:last-child td{border-bottom:none}
            td.num{font-variant-numeric:tabular-nums}
            .repo{font-weight:600;color:var(--ink)}
            .badge{display:inline-block;padding:2px 8px;border-radius:999px;font-size:12px;font-weight:600}
            .pass{background:rgba(46,160,67,.15);color:var(--good)} .fail{background:rgba(229,83,75,.15);color:var(--bad)} .na{color:var(--muted)}
            .hl{color:var(--accent);font-weight:600}
            .note{color:var(--muted);margin-top:14px;font-size:13px}
            footer{color:var(--muted);margin-top:22px;font-size:12px}
            """);
        sb.Append("</style></head><body><div class=\"wrap\">");

        sb.Append("<h1>CodeCompass benchmark</h1>");
        sb.Append($"<p class=\"sub\">Indexing throughput, query latency, and correctness across {rows.Count} repositor{(rows.Count == 1 ? "y" : "ies")}.</p>");

        sb.Append("<div class=\"meta\">");
        Chip(sb, "When", meta.Timestamp);
        Chip(sb, "Machine", meta.Machine);
        Chip(sb, "OS", meta.Os);
        Chip(sb, "Cores", meta.Cores.ToString());
        Chip(sb, "Runtime", meta.Runtime);
        sb.Append("</div>");

        sb.Append("<table><thead><tr>");
        foreach (var h in new[] { "Repo", "Lang", "Files", "Text MB", "Build s", "MB/s", "MB/s/core", "Cores", "Index x", "p50 ms", "p95 ms", "p99 ms", "Incr s", "Heap MB", "Peak MB", "Correct" })
            sb.Append($"<th>{h}</th>");
        sb.Append("</tr></thead><tbody>");

        foreach (var r in rows)
        {
            var b = r.Bench;
            sb.Append("<tr>");
            sb.Append($"<td class=\"repo\">{Enc(r.Id)}</td>");
            sb.Append($"<td>{Enc(r.Language)}</td>");
            Num(sb, $"{b.Files:N0}");
            Num(sb, $"{b.Bytes / (1024.0 * 1024.0):N1}");
            Num(sb, $"{b.BuildSeconds:N2}");
            sb.Append($"<td class=\"num hl\">{b.BuildMBps:N1}</td>");
            Num(sb, $"{b.BuildMBpsPerCore:N1}");
            Num(sb, b.Cores.ToString());
            Num(sb, $"{b.IndexRatio:N2}");
            Num(sb, $"{b.QueryP50Ms:N2}");
            Num(sb, $"{b.QueryP95Ms:N2}");
            Num(sb, $"{b.QueryP99Ms:N2}");
            Num(sb, $"{b.IncrementalSeconds:N3}");
            Num(sb, $"{b.ManagedHeapMb:N0}");
            Num(sb, $"{b.PeakWorkingSetMb:N0}");
            sb.Append($"<td>{CorrectnessBadge(r.Correctness)}</td>");
            sb.Append("</tr>");
        }
        sb.Append("</tbody></table>");

        if (skipped.Count > 0)
            sb.Append($"<p class=\"note\">Skipped (not fetched): {Enc(string.Join(", ", skipped))}. Run <code>fetch-corpus.ps1</code> or <code>bench fetch</code> first.</p>");

        sb.Append("<footer>Generated by CodeCompass.Bench. MB/s is indexing throughput; Index x is on-disk index size relative to source; Correct = trigram search vs brute-force scan on real files.</footer>");
        sb.Append("</div></body></html>");
        return sb.ToString();
    }

    private static void Chip(StringBuilder sb, string k, string v) =>
        sb.Append($"<span class=\"chip\">{Enc(k)} <b>{Enc(v)}</b></span>");

    private static void Num(StringBuilder sb, string v) => sb.Append($"<td class=\"num\">{v}</td>");

    private static string CorrectnessBadge(string correctness) => correctness switch
    {
        "PASS" => "<span class=\"badge pass\">PASS</span>",
        "—" => "<span class=\"na\">-</span>",
        _ => $"<span class=\"badge fail\">{Enc(correctness)}</span>",
    };

    private static string Enc(string s) => WebUtility.HtmlEncode(s);
}
