<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CodeCompass.Core\CodeCompass.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClangSharp" Version="20.1.2" />
    <PackageReference Include="libclang.runtime.win-x64" Version="20.1.2" />
    <PackageReference Include="libClangSharp.runtime.win-x64" Version="20.1.2" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.9.2" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

</Project>
